/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lider_Tecnico;

import Login.Login;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis
 */
public class Riesgos extends javax.swing.JFrame {

    /**
     * Creates new form Riesgos
     */
    BDRiesgos mBD = new BDRiesgos();
    DefaultTableModel ModeloTabla = new DefaultTableModel();
    boolean listo = false;
    int ID = 0;

    public Riesgos() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Llena los combobox de cada pestaña ddel formulario
        CBProyecto.removeAllItems();
        CBProyecto1.removeAllItems();
        CBProyecto2.removeAllItems();
        CBProyecto3.removeAllItems();
        if (mBD.ConectarRiesgos()) {
            mBD.ComboClaveProyecto(CBProyecto);
            mBD.ComboClaveProyecto(CBProyecto1);
            mBD.ComboClaveProyecto(CBProyecto2);
            mBD.ComboClaveProyecto(CBProyecto3);
            listo = true;
        } else {
            JOptionPane.showMessageDialog(null, "Error BD");
        }
        mBD.DesconectarRiesgos();

        IMG.Fondo Fondoq = new IMG.Fondo(Fondo);
        Fondo.add(Fondoq).repaint();
        Fondo.setOpaque(false);
        Fondo.setBorder(null);
        Fondo.setBackground(new Color(0, 0, 0, 64));
        //Pestaña 1
        IMG.Fondo FondoA = new IMG.Fondo(Fondo1);
        Fondo1.add(FondoA).repaint();
        Fondo1.setOpaque(false);
        Fondo1.setBorder(null);
        Fondo1.setBackground(new Color(0, 0, 0, 64));
        //Pestaña2
        IMG.Fondo Fondob = new IMG.Fondo(Fondo2);
        Fondo2.add(Fondob).repaint();
        Fondo2.setOpaque(false);
        Fondo2.setBorder(null);
        Fondo2.setBackground(new Color(0, 0, 0, 64));
        //Pestaña3
        IMG.Fondo Fondoc = new IMG.Fondo(Fondo3);
        Fondo3.add(Fondoc).repaint();
        Fondo3.setOpaque(false);
        Fondo3.setBorder(null);
        Fondo3.setBackground(new Color(0, 0, 0, 64));
        //Pestaña4
        IMG.Fondo Fondom = new IMG.Fondo(Fondo4);
        Fondo4.add(Fondom).repaint();
        Fondo4.setOpaque(false);
        Fondo4.setBorder(null);
        Fondo4.setBackground(new Color(0, 0, 0, 64));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Fondo1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CBProyecto = new javax.swing.JComboBox<>();
        TxtTitulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtDes = new javax.swing.JTextArea();
        BtnAceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Fondo2 = new javax.swing.JPanel();
        BtnDel = new javax.swing.JButton();
        CBProyecto1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBRiesgos = new javax.swing.JTable();
        TxtID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Fondo3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        CBProyecto3 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        TxtTituo1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TxtDes1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        TBRiesgosM = new javax.swing.JTable();
        BtnModificar = new javax.swing.JButton();
        Fondo4 = new javax.swing.JPanel();
        CBProyecto2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TBRiesgosC = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Riesgos");

        jLabel1.setText("Clave de Proyecto: ");

        jLabel2.setText("Titulo: ");

        jLabel3.setText("Descripcion: ");

        CBProyecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBProyecto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBProyectoItemStateChanged(evt);
            }
        });

        TxtDes.setColumns(20);
        TxtDes.setLineWrap(true);
        TxtDes.setRows(5);
        jScrollPane1.setViewportView(TxtDes);

        BtnAceptar.setText("Aceptar");
        BtnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAceptarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAceptarMouseExited(evt);
            }
        });

        jButton2.setText("Cancelar");

        javax.swing.GroupLayout Fondo1Layout = new javax.swing.GroupLayout(Fondo1);
        Fondo1.setLayout(Fondo1Layout);
        Fondo1Layout.setHorizontalGroup(
            Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Fondo1Layout.createSequentialGroup()
                        .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(jButton2))
                    .addGroup(Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CBProyecto, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1)))
                .addGap(36, 36, 36))
        );
        Fondo1Layout.setVerticalGroup(
            Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CBProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Fondo1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel3))
                    .addGroup(Fondo1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addGroup(Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(BtnAceptar))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alta", Fondo1);

        BtnDel.setText("Eliminar");
        BtnDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnDelMouseClicked(evt);
            }
        });

        CBProyecto1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBProyecto1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBProyecto1ItemStateChanged(evt);
            }
        });

        jLabel6.setText("Clave de Proyecto: ");

        TBRiesgos.setModel(ModeloTabla);
        TBRiesgos.setEnabled(false);
        TBRiesgos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBRiesgosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TBRiesgos);

        TxtID.setEnabled(false);

        jLabel4.setText("ID de Riesgo");

        javax.swing.GroupLayout Fondo2Layout = new javax.swing.GroupLayout(Fondo2);
        Fondo2.setLayout(Fondo2Layout);
        Fondo2Layout.setHorizontalGroup(
            Fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(Fondo2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(Fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(Fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo2Layout.createSequentialGroup()
                                .addComponent(TxtID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CBProyecto1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Fondo2Layout.setVerticalGroup(
            Fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CBProyecto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDel)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addGap(51, 51, 51))
        );

        jTabbedPane1.addTab("Baja", Fondo2);

        jLabel7.setText("Clave de Proyecto: ");

        CBProyecto3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBProyecto3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBProyecto3ItemStateChanged(evt);
            }
        });

        jLabel8.setText("Titulo: ");

        TxtTituo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTituo1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Descripcion: ");

        TxtDes1.setColumns(20);
        TxtDes1.setLineWrap(true);
        TxtDes1.setRows(5);
        jScrollPane4.setViewportView(TxtDes1);

        TBRiesgosM.setModel(ModeloTabla);
        TBRiesgosM.setEnabled(false);
        TBRiesgosM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBRiesgosMMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TBRiesgosM);

        BtnModificar.setText("Modificar");
        BtnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnModificarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Fondo3Layout = new javax.swing.GroupLayout(Fondo3);
        Fondo3.setLayout(Fondo3Layout);
        Fondo3Layout.setHorizontalGroup(
            Fondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Fondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Fondo3Layout.createSequentialGroup()
                        .addGroup(Fondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(Fondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtTituo1)
                            .addComponent(jScrollPane4)))
                    .addGroup(Fondo3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(CBProyecto3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 89, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(Fondo3Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(BtnModificar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Fondo3Layout.setVerticalGroup(
            Fondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(Fondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CBProyecto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(Fondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtTituo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(32, 32, 32)
                .addGroup(Fondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(62, 62, 62))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnModificar)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Modificacion", Fondo3);

        CBProyecto2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBProyecto2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBProyecto2ItemStateChanged(evt);
            }
        });

        jLabel5.setText("Clave de Proyecto: ");

        TBRiesgosC.setModel(ModeloTabla);
        jScrollPane3.setViewportView(TBRiesgosC);

        javax.swing.GroupLayout Fondo4Layout = new javax.swing.GroupLayout(Fondo4);
        Fondo4.setLayout(Fondo4Layout);
        Fondo4Layout.setHorizontalGroup(
            Fondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(CBProyecto2, 0, 317, Short.MAX_VALUE)
                .addGap(37, 37, 37))
            .addGroup(Fondo4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        Fondo4Layout.setVerticalGroup(
            Fondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(Fondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CBProyecto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("Consulta", Fondo4);

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Inicio");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu9.setText("Asignacion de Riesgos");
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu9);

        jMenu3.setText("Acciones de Mitigacion");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu10.setText("Acciones de Contingencia");
        jMenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu10MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu10);

        jMenu4.setText("Matriz de Riesgos");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Salir");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAceptarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAceptarMouseExited

    private void CBProyecto1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBProyecto1ItemStateChanged
        // Llena la tabla en a pestaña de Baja de riesgo
        if (listo) {
            if (mBD.ConectarRiesgos()) {
                String C = "";
                C = CBProyecto1.getSelectedItem().toString();
                ResultSet ListaE = mBD.ConsultaRiesgos(C);

                this.TBRiesgos.setModel(Convertidor.convertir(ListaE));
            }
            mBD.DesconectarRiesgos();
        }
    }//GEN-LAST:event_CBProyecto1ItemStateChanged

    private void CBProyectoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBProyectoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CBProyectoItemStateChanged

    private void CBProyecto3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBProyecto3ItemStateChanged
        // TODO add your handling code here:
        if (listo) {
            if (mBD.ConectarRiesgos()) {
                String C = "";
                C = CBProyecto3.getSelectedItem().toString();
                ResultSet ListaM = mBD.ConsultaRiesgos(C);

                this.TBRiesgosM.setModel(Convertidor.convertir(ListaM));
            }
            mBD.DesconectarRiesgos();
        }
    }//GEN-LAST:event_CBProyecto3ItemStateChanged

    private void CBProyecto2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBProyecto2ItemStateChanged
        // Llena la tabla en a pestaña de Consulta de riesgo
        if (listo) {
            if (mBD.ConectarRiesgos()) {
                String C = "";
                C = CBProyecto2.getSelectedItem().toString();
                ResultSet ListaC = mBD.ConsultaRiesgos(C);

                this.TBRiesgosC.setModel(Convertidor.convertir(ListaC));
            }
            mBD.DesconectarRiesgos();
        }
    }//GEN-LAST:event_CBProyecto2ItemStateChanged

    private void TBRiesgosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBRiesgosMouseClicked
        // Obtiene ID del riesgo seleccionado en la tabla ubicada en la pestaña de baja
        int Seleccion = 0;
        ID = 0;
        this.TxtID.setText("");
        Seleccion = this.TBRiesgos.rowAtPoint(evt.getPoint());
        this.TxtID.setText(this.TBRiesgos.getModel().getValueAt(Seleccion, 1).toString());
        ID = Integer.parseInt(TBRiesgos.getModel().getValueAt(Seleccion, 0).toString());
    }//GEN-LAST:event_TBRiesgosMouseClicked

    private void BtnDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDelMouseClicked
        // Verifica que el ID se haya obtenido
        if (this.TxtID.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Selecione un riesgo antes");
        } else {
            if (mBD.ConectarRiesgos()) {
                //Elimina el riesgo seleccionado
                if (mBD.EliminarRiesgo(ID)) {
                    JOptionPane.showMessageDialog(null, "Riesgo dado de baja");
                    TxtID.setText("");
                    BorrarE();
                    CBProyecto1.setSelectedIndex(0);
                } else {
                    JOptionPane.showMessageDialog(null, "Error al Eliminar");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
            mBD.DesconectarRiesgos();
        }
    }//GEN-LAST:event_BtnDelMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        PrincipalLider mP = new PrincipalLider();
        mP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
        // TODO add your handling code here:
        AsignarRiesgo mAR = new AsignarRiesgo();
        mAR.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu9MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        Mitigacion mM = new Mitigacion();
        mM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu10MouseClicked
        // TODO add your handling code here:
        Contingencia mC = new Contingencia();
        mC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu10MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        Matriz mMZ = new Matriz();
        mMZ.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        Login mL = new Login();
        mL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu5MouseClicked

    private void TBRiesgosMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBRiesgosMMouseClicked
        // Obtiene el ID del riesgo seleccionado y muestra e titulo y descripcion en las cajas de texto
        int Seleccion = 0;
        ID = 0;
        Seleccion = this.TBRiesgosM.rowAtPoint(evt.getPoint());
        this.TxtTituo1.setText(this.TBRiesgosM.getModel().getValueAt(Seleccion, 1).toString());
        this.TxtDes1.setText(this.TBRiesgosM.getModel().getValueAt(Seleccion, 2).toString());
        ID = Integer.parseInt(TBRiesgosM.getModel().getValueAt(Seleccion, 0).toString());

    }//GEN-LAST:event_TBRiesgosMMouseClicked

    private void BtnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnModificarMouseClicked
        // Verifica que los campos necesarios no esten vacios
        if (this.TxtTituo1.equals("") || this.TxtDes1.equals("") || CBProyecto3.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un Riesgo y llene los campos");
        } else {
            if (mBD.ConectarRiesgos()) {

                Riesgo mRiesgo = new Riesgo();
                Riesgo nRiesgo = new Riesgo();
                String T1 = "";

                mRiesgo.setClave(TxtID.getText());
                nRiesgo.setTitulo(TxtTituo1.getText());
                nRiesgo.setDetalles(TxtDes1.getText());
                //Modifica el riesgo seleccionado
                if (mBD.ModificarRiesgo(mRiesgo, nRiesgo)) {
                    JOptionPane.showMessageDialog(null, "Proyecto Modificado con Exito");
                    TxtID.setText("");
                    TxtTituo1.setText("");
                    TxtDes1.setText((""));
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error en la BD");
            }
            mBD.DesconectarRiesgos();
        }
    }//GEN-LAST:event_BtnModificarMouseClicked

    private void TxtTituo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTituo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTituo1ActionPerformed

    private void BtnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAceptarMouseClicked
        // Verifica que los campos necesarios no esten vacios
        if ((CBProyecto.getSelectedIndex() == 0)) {
            JOptionPane.showMessageDialog(null, "Llene los Campos antes de Guardar");
        } else if ((this.TxtTitulo.getText() == "")) {
            JOptionPane.showMessageDialog(null, "Llene los Campos antes de Guardar");
        } else if ((TxtDes.getText() == "")) {
            JOptionPane.showMessageDialog(null, "Llene los Campos antes de Guardar");
        } else {
            Riesgo mRiesgo = new Riesgo();
            mRiesgo.setClave(CBProyecto.getSelectedItem().toString());
            mRiesgo.setTitulo(TxtTitulo.getText());
            mRiesgo.setDetalles(TxtDes.getText());

            if (mBD.ConectarRiesgos()) {
                //Da de alta el riesgo
                if (mBD.AgregarRiesgo(mRiesgo)) {
                    JOptionPane.showMessageDialog(null, "Riesgo dado de Alta exitosamente");
                    CBProyecto.setSelectedIndex(0);
                    TxtTitulo.setText("");
                    TxtDes.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al dar de Alta");
                }
            }
        }
    }//GEN-LAST:event_BtnAceptarMouseClicked

        void BorrarE
        
            () {
        DefaultTableModel LimpiadoTabla = (DefaultTableModel) TBRiesgos.getModel();
            //Borramosla tabla...
            int c = TBRiesgos.getRowCount() - 1;

            for (int i = c; i >= 0; i--) {
                LimpiadoTabla.removeRow(LimpiadoTabla.getRowCount() - 1);
            }
        }

        void BorrarM
        
            () {
        DefaultTableModel LimpiadoTabla = (DefaultTableModel) TBRiesgosM.getModel();
            //Borramosla tabla...
            int c = TBRiesgosM.getRowCount() - 1;

            for (int i = c; i >= 0; i--) {
                LimpiadoTabla.removeRow(LimpiadoTabla.getRowCount() - 1);
            }
        }
        /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Riesgos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Riesgos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Riesgos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Riesgos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Riesgos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnDel;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JComboBox<String> CBProyecto;
    private javax.swing.JComboBox<String> CBProyecto1;
    private javax.swing.JComboBox<String> CBProyecto2;
    private javax.swing.JComboBox<String> CBProyecto3;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Fondo1;
    private javax.swing.JPanel Fondo2;
    private javax.swing.JPanel Fondo3;
    private javax.swing.JPanel Fondo4;
    private javax.swing.JTable TBRiesgos;
    private javax.swing.JTable TBRiesgosC;
    private javax.swing.JTable TBRiesgosM;
    private javax.swing.JTextArea TxtDes;
    private javax.swing.JTextArea TxtDes1;
    private javax.swing.JTextField TxtID;
    private javax.swing.JTextField TxtTitulo;
    private javax.swing.JTextField TxtTituo1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
