/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Administrador.PrincipalAdmin;
import Desarrollador.PrincipalDesarrollador;
import Desarrollador.Usuario;
import Lider_Tecnico.PrincipalLider;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    BD mBD = new BD();
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtUser = new javax.swing.JTextField();
        TxtPass = new javax.swing.JPasswordField();
        BtnLogin = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setPreferredSize(new java.awt.Dimension(303, 411));
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        TxtUser.setBackground(new java.awt.Color(0, 0, 0));
        TxtUser.setForeground(new java.awt.Color(255, 255, 255));
        TxtUser.setBorder(null);
        getContentPane().add(TxtUser);
        TxtUser.setBounds(80, 200, 160, 30);

        TxtPass.setBackground(new java.awt.Color(0, 0, 0));
        TxtPass.setForeground(new java.awt.Color(255, 255, 255));
        TxtPass.setBorder(null);
        getContentPane().add(TxtPass);
        TxtPass.setBounds(80, 250, 160, 30);

        BtnLogin.setText("Aceptar");
        BtnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLoginMouseClicked(evt);
            }
        });
        getContentPane().add(BtnLogin);
        BtnLogin.setBounds(60, 320, 71, 23);

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalir);
        BtnSalir.setBounds(170, 320, 71, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/login.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -30, 300, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLoginMouseClicked
        if (TxtUser.equals("") || TxtPass.equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese Nombre de usuario o Correo Electronico y Contraseña");
        } else {
            if (mBD.Conectar()) {
                String User, Pass, UserC, PassC, Tipo, Email = "";
                
                User = TxtUser.getText();
                Pass = TxtPass.getText();
                UserC = mBD.ConsultaUser(User);
                PassC = mBD.ConsultaPassword(User);
                Email = mBD.ConsultaCorreo(User);
                
                if (User.equals(UserC) || User.equals(Email) ) {
                    if (Pass.equals(PassC)) {
                        Tipo = mBD.ConsultaTipo(User);
                        
                        switch (Tipo){
                            case "Administrador":
                                PrincipalAdmin Admin = new PrincipalAdmin();
                                Admin.setVisible(true);
                                this.dispose();
                                break;
                            case "Lider Tecnico":
                                PrincipalLider Lider = new PrincipalLider();
                                Lider.setVisible(true);
                                this.dispose();
                                break;
                            case "Desarrollador":
                                int ID = 0;
                                ID = mBD.ConsultaID(User);
                                Usuario.IdUser = ID;
                                PrincipalDesarrollador Des = new PrincipalDesarrollador();
                                Des.setVisible(true);;
                                this.dispose();
                                break;
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Contraseña Invalida");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Usuario o Correo Invalidos");
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
            mBD.Desconectar();
        }
        
    }//GEN-LAST:event_BtnLoginMouseClicked

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_BtnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogin;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JPasswordField TxtPass;
    private javax.swing.JTextField TxtUser;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
