/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrador;

import Login.Login;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

/**
 *
 * @author Luis
 */
public class Proyectos extends javax.swing.JFrame {

    BDProyecto mBD = new BDProyecto();
    SimpleDateFormat formatofecha = new SimpleDateFormat("yyyy/MM/dd");
    DefaultTableModel ModeloTabla = new DefaultTableModel();
    String Clave = "";
    String ClaveM = "";

    public Proyectos() {
        initComponents();
        setFilas();
        IMG.Fondo Fondoq = new IMG.Fondo(Fondo);
        Fondo.add(Fondoq).repaint();
        Fondo.setOpaque(false);
        Fondo.setBorder(null);
        Fondo.setBackground(new Color(0, 0, 0, 64));
        //Pestaña 1
        IMG.Fondo FondoA = new IMG.Fondo(Fondo1);
        Fondo1.add(FondoA).repaint();
        Fondo1.setOpaque(false);
        Fondo1.setBorder(null);
        Fondo1.setBackground(new Color(0, 0, 0, 64));
        //Pestaña2
        IMG.Fondo Fondob = new IMG.Fondo(Fondo2);
        Fondo2.add(Fondob).repaint();
        Fondo2.setOpaque(false);
        Fondo2.setBorder(null);
        Fondo2.setBackground(new Color(0, 0, 0, 64));
        //Pestaña3
        IMG.Fondo Fondoc = new IMG.Fondo(Fondo3);
        Fondo3.add(Fondoc).repaint();
        Fondo3.setOpaque(false);
        Fondo3.setBorder(null);
        Fondo3.setBackground(new Color(0, 0, 0, 64));
        //Pestaña4
        IMG.Fondo Fondom = new IMG.Fondo(Fondo4);
        Fondo4.add(Fondom).repaint();
        Fondo4.setOpaque(false);
        Fondo4.setBorder(null);
        Fondo4.setBackground(new Color(0, 0, 0, 64));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Fondo1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtClave = new javax.swing.JTextField();
        TxtNom = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtDes = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Inicio = new com.toedter.calendar.JDateChooser();
        Fin = new com.toedter.calendar.JDateChooser();
        BtnAdd = new javax.swing.JButton();
        BtnCan = new javax.swing.JButton();
        Fondo2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBProyecto = new javax.swing.JTable();
        TxtEliminar = new javax.swing.JTextField();
        BtnEliminar = new javax.swing.JButton();
        Fondo3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TBProyecto3 = new javax.swing.JTable();
        TxtCriterio = new javax.swing.JTextField();
        Fondo4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TBProyecto4 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        TxtNom1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TxtDes1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Proyectos");
        setResizable(false);

        jLabel1.setText("Clave: ");

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Descripcion: ");

        TxtDes.setColumns(20);
        TxtDes.setLineWrap(true);
        TxtDes.setRows(5);
        jScrollPane1.setViewportView(TxtDes);

        jLabel4.setText("Fecha de Inicio:");

        jLabel5.setText("Fecha Fin: ");

        BtnAdd.setText("Agregar");
        BtnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAddMouseClicked(evt);
            }
        });

        BtnCan.setText("Cancelar");

        javax.swing.GroupLayout Fondo1Layout = new javax.swing.GroupLayout(Fondo1);
        Fondo1.setLayout(Fondo1Layout);
        Fondo1Layout.setHorizontalGroup(
            Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Fondo1Layout.createSequentialGroup()
                        .addGroup(Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fin, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Fondo1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Fondo1Layout.createSequentialGroup()
                            .addGroup(Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(30, 30, 30)
                            .addGroup(Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Fondo1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(BtnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCan)
                .addContainerGap())
        );

        Fondo1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Fin, Inicio, TxtClave, TxtNom, jScrollPane1});

        Fondo1Layout.setVerticalGroup(
            Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Fondo1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5))
                    .addGroup(Fondo1Layout.createSequentialGroup()
                        .addComponent(Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAdd)
                    .addComponent(BtnCan))
                .addGap(24, 24, 24))
        );

        jTabbedPane1.addTab("Alta", Fondo1);

        TBProyecto.setModel(ModeloTabla);
        TBProyecto.setEnabled(false);
        TBProyecto.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TBProyectoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        TBProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBProyectoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TBProyecto);

        TxtEliminar.setEnabled(false);

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Fondo2Layout = new javax.swing.GroupLayout(Fondo2);
        Fondo2.setLayout(Fondo2Layout);
        Fondo2Layout.setHorizontalGroup(
            Fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(Fondo2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(TxtEliminar)
                .addGap(18, 18, 18)
                .addComponent(BtnEliminar)
                .addGap(28, 28, 28))
        );
        Fondo2Layout.setVerticalGroup(
            Fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(Fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Baja", Fondo2);

        TBProyecto3.setModel(ModeloTabla);
        jScrollPane3.setViewportView(TBProyecto3);

        TxtCriterio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCriterioKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout Fondo3Layout = new javax.swing.GroupLayout(Fondo3);
        Fondo3.setLayout(Fondo3Layout);
        Fondo3Layout.setHorizontalGroup(
            Fondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(Fondo3Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(TxtCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Fondo3Layout.setVerticalGroup(
            Fondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(TxtCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta", Fondo3);

        TBProyecto4.setModel(ModeloTabla);
        TBProyecto4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBProyecto4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TBProyecto4);

        jLabel10.setText("Nombre: ");

        TxtNom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNom1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Descripcion: ");

        TxtDes1.setColumns(20);
        TxtDes1.setLineWrap(true);
        TxtDes1.setRows(5);
        jScrollPane5.setViewportView(TxtDes1);

        jButton1.setText("Modificar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Cancelar");

        javax.swing.GroupLayout Fondo4Layout = new javax.swing.GroupLayout(Fondo4);
        Fondo4.setLayout(Fondo4Layout);
        Fondo4Layout.setHorizontalGroup(
            Fondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(43, 43, 43))
            .addGroup(Fondo4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(Fondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Fondo4Layout.createSequentialGroup()
                        .addGroup(Fondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Fondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TxtNom1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        Fondo4Layout.setVerticalGroup(
            Fondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Fondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(TxtNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Fondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Fondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Modificar", Fondo4);

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setEnabled(false);

        jMenu5.setText("Inicio");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu1.setText("Proyectos");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Usuarios");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Matriz De Riesgos");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Salir");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        PrincipalAdmin mAdmin = new PrincipalAdmin();
        mAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        Proyectos mProyectos = new Proyectos();
        this.dispose();
        mProyectos.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        Usuarios mUsuarios = new Usuarios();
        mUsuarios.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        Matriz mMatriz = new Matriz();
        mMatriz.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        Login mLogin = new Login();
        mLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void TBProyectoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TBProyectoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TBProyectoAncestorAdded

    private void TBProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBProyectoMouseClicked
        // TODO add your handling code here:
        int Seleccion = 0;
        this.TxtEliminar.setText("");
        Seleccion = this.TBProyecto.rowAtPoint(evt.getPoint());
        this.TxtEliminar.setText(this.TBProyecto.getModel().getValueAt(Seleccion, 1).toString());
        Clave = TBProyecto.getModel().getValueAt(Seleccion, 0).toString();
    }//GEN-LAST:event_TBProyectoMouseClicked

    private void BtnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseClicked
        // TODO add your handling code here:
        if (TxtEliminar.equals("")) {
            JOptionPane.showMessageDialog(null, "Seleccine un proyecto");
        } else {
            if (mBD.ConectarProyecto()) {
                if (mBD.EliminarProyecto(Clave)) {
                    JOptionPane.showMessageDialog(null, "Proyecto Dado de Baja");
                    TxtEliminar.setText("");
                    Borrar();
                    Llenar();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al dar de Baja");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error en a BD");
            }
        }
    }//GEN-LAST:event_BtnEliminarMouseClicked

    private void TxtCriterioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCriterioKeyTyped
        // TODO add your handling code here:
        if (this.TxtCriterio.equals("")) {
            Borrar();
            Llenar();
        }
        BorrarC();
        if (this.mBD.ConectarProyecto()) {
            ResultSet Lista = null;
            Lista = mBD.ConsultaFiltroP(TxtCriterio.getText());
            this.TBProyecto3.setModel(Convertidor.convertir(Lista));
        } else {
            JOptionPane.showMessageDialog(null, "Error en BD");
        }
    }//GEN-LAST:event_TxtCriterioKeyTyped

    private void BtnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAddMouseClicked
        // TODO add your handling code here:
        if (TxtClave.equals("") || TxtNom.equals("") || TxtDes.equals("") || Inicio.equals(null) || Fin.equals(null)) {
            JOptionPane.showMessageDialog(null, "Llena los campos antes de guardar");
        } else {
            if (mBD.ConectarProyecto()) {
                Proyecto mProyecto = new Proyecto();
                mProyecto.setClave(TxtClave.getText());
                mProyecto.setNombre(TxtNom.getText());
                mProyecto.setDescripcion(TxtDes.getText());
                mProyecto.setFechaInicio(formatofecha.format(Inicio.getDate()));
                mProyecto.setFechaFin(formatofecha.format(Fin.getDate()));

                if (mBD.AgregarProyecto(mProyecto)) {
                    JOptionPane.showMessageDialog(null, "Proyecto Agreagado con Exito");
                    Borrar();
                    Llenar();
                    TxtClave.setText("");
                    TxtNom.setText("");
                    TxtDes.setText("");
                    Inicio.setDate(null);
                    Fin.setDate(null);
                } else {
                    JOptionPane.showMessageDialog(null, "Error en BD");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error en BD");
            }
            mBD.DesconectarProyecto();
        }
    }//GEN-LAST:event_BtnAddMouseClicked

    private void TxtNom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNom1ActionPerformed

    private void TBProyecto4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBProyecto4MouseClicked
        // TODO add your handling code here:
        int Seleccion = 0;
        ClaveM = "";
        this.TxtNom1.setText("");
        this.TxtDes1.setText("");
        Seleccion = this.TBProyecto.rowAtPoint(evt.getPoint());
        this.TxtNom1.setText(this.TBProyecto4.getModel().getValueAt(Seleccion, 1).toString());
        this.TxtDes1.setText(this.TBProyecto4.getModel().getValueAt(Seleccion, 2).toString());/*
        this.Inicio1.setDate(this.formatofecha.format(this.TBProyecto4.getModel().getValueAt(Seleccion, 3).toString()));
        this.Fin1.setDateFormatString(this.TBProyecto4.getModel().getValueAt(Seleccion, 4).toString());*/
        ClaveM = TBProyecto.getModel().getValueAt(Seleccion, 0).toString();
    }//GEN-LAST:event_TBProyecto4MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if (TxtNom1.equals("") || TxtDes1.equals("") || ClaveM.equals("")) {
            JOptionPane.showMessageDialog(null, "Seleccione un Proyecto y llene los campos a modificar");
        } else {
            Proyecto mP = new Proyecto();
            mP.setClave(ClaveM);
            mP.setNombre(TxtNom1.getText());
            mP.setDescripcion(TxtDes1.getText());

            if (mBD.ConectarProyecto()) {
                if (mBD.ModificarProyecto(mP)) {
                    JOptionPane.showMessageDialog(null, "Modificacion realizada con exito");
                    TxtNom1.setText("");
                    TxtDes1.setText("");
                    Borrar();
                    this.Llenar();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error en BD");
            }
            mBD.DesconectarProyecto();

        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void Llenar() {
        if (mBD.ConectarProyecto()) {
            ResultSet ListaE = mBD.ConsultaProyectos();
            ResultSet ListaM = mBD.ConsultaProyectos();
            ResultSet ListaC = mBD.ConsultaProyectos();

            this.TBProyecto.setModel(Convertidor.convertir(ListaE));
            this.TBProyecto4.setModel(Convertidor.convertir(ListaM));
            this.TBProyecto3.setModel(Convertidor.convertir(ListaC));
        } else {
            JOptionPane.showMessageDialog(null, "Error al consultar...");
        }
        mBD.DesconectarProyecto();
    }

    void Borrar() {
        DefaultTableModel LimpiadoTabla = (DefaultTableModel) TBProyecto.getModel();
        DefaultTableModel LimpiadoTabla2 = (DefaultTableModel) TBProyecto3.getModel();
        DefaultTableModel LimpiadoTabla3 = (DefaultTableModel) TBProyecto4.getModel();
        //Borramosla tabla...
        int a = TBProyecto.getRowCount() - 1;
        int m = TBProyecto4.getRowCount() - 1;
        int c = TBProyecto3.getRowCount() - 1;

        for (int i = a; i >= 0; i--) {
            LimpiadoTabla.removeRow(LimpiadoTabla.getRowCount() - 1);
        }

        for (int i = m; i >= 0; i--) {
            LimpiadoTabla3.removeRow(LimpiadoTabla3.getRowCount() - 1);
        }

        for (int i = c; i >= 0; i--) {
            LimpiadoTabla2.removeRow(LimpiadoTabla2.getRowCount() - 1);
        }
    }

    void BorrarC() {

        DefaultTableModel LimpiadoTabla2 = (DefaultTableModel) TBProyecto3.getModel();
        //Borramosla tabla...        
        int c = TBProyecto3.getRowCount() - 1;

        for (int i = c; i >= 0; i--) {
            LimpiadoTabla2.removeRow(LimpiadoTabla2.getRowCount() - 1);
        }
    }

    private void setFilas() {
        if (mBD.ConectarProyecto()) {

            ResultSet ListaE = mBD.ConsultaProyectos();
            ResultSet ListaM = mBD.ConsultaProyectos();
            ResultSet ListaC = mBD.ConsultaProyectos();

            this.TBProyecto.setModel(Convertidor.convertir(ListaE));
            this.TBProyecto3.setModel(Convertidor.convertir(ListaM));
            this.TBProyecto4.setModel(Convertidor.convertir(ListaC));
        }
        mBD.DesconectarProyecto();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proyectos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proyectos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proyectos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proyectos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proyectos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnCan;
    private javax.swing.JButton BtnEliminar;
    private com.toedter.calendar.JDateChooser Fin;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Fondo1;
    private javax.swing.JPanel Fondo2;
    private javax.swing.JPanel Fondo3;
    private javax.swing.JPanel Fondo4;
    private com.toedter.calendar.JDateChooser Inicio;
    private javax.swing.JTable TBProyecto;
    private javax.swing.JTable TBProyecto3;
    private javax.swing.JTable TBProyecto4;
    private javax.swing.JTextField TxtClave;
    private javax.swing.JTextField TxtCriterio;
    private javax.swing.JTextArea TxtDes;
    private javax.swing.JTextArea TxtDes1;
    private javax.swing.JTextField TxtEliminar;
    private javax.swing.JTextField TxtNom;
    private javax.swing.JTextField TxtNom1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
